### ISSUE TITLE
Instantiating multiple blinds through one scan

### ISSUE THREAD

**Issue by binsentsu** [breitburg/python-am43#1]
Hi,
When creating multiple blind instances the BLE scanning is performed for every blind.
Would be nice if initialization off multiple Blinds were possible through one BLE scan.
Mayb some kind of static factory method taking a list of MACs?

**Comment by breitburg** [comment]
Hello. Thank you, good idea! I'll write an implementation of that today

**Comment by breitburg** [comment]
I've implemented that and pushed to the [`multiple`](https://github.com/breitburg/python-am43/tree/multiple) branch. @binsentsu can you please try this out. If you confirm that everything is all-right I will merge it.

Now you can search blinds using `am43.search` method like that:

```python
import am43

# Single blind
blind = am43.search('xx:xx:xx:xx:xx:xx')
blind.set_position(percentage=30)

# Multiple blinds
blinds = am43.search('xx:xx:xx:xx:xx:xx', 'xx:xx:xx:xx:xx:xx', 'xx:xx:xx:xx:xx:xx', ...)
for blind in blinds:
    blind.set_position(percentage=30)
```

**Comment by binsentsu** [comment]
The search functionality is working fine, but there were some regressions with the refactoring of reconnect and retry.
Proposed some changed in PR #2 
Feel free to add your remarks/questions in the PR.

**Comment by breitburg** [comment]
Thanks for your work! All your changes that you have made complement the library very well indeed. I merge the `master` and `multiple` branches.
