### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by ostgardh** [breitburg/python-am43#4]
I have try this code, but I get always list index out of range.

My code is:

```python
import am43

blind = am43.search('02:30:F4:98:89:77')  # Returns single blind
blind.set_position(percentage=30)  # Sets blinds position
```

**Comment by breitburg** [comment]
Hey! Can you please provide full traceback. Looks like you have issue with the `bluepy` library.

**Comment by breitburg** [comment]
List index out of range means that there is no blinds were discovered with the specified address. I guess that this is a hardware problem or wrong address.
