### ISSUE TITLE
Cannot find blinds even though they are seen by hcitool

### ISSUE THREAD

**Issue by AdamWeglarz** [breitburg/python-am43#6]
Hi,

I have problem. 
blinds are seen by RPI without issue
pi@drukarka:~ $ sudo hcitool lescan
LE Scan ...
02:8A:99:AE:55:9C Sypialnia lewa
02:EA:37:54:38:26 sypialnia prawe
But I cannot connect:

pi@drukarka:~ $ sudo python3
Python 3.7.3 (default, Jul 25 2020, 13:03:44)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import am43
>>> blind = am43.search('02:8A:99:AE:55:9C')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/am43/search.py", line 6, in search
    return blinds[0] if len(addresses) == 1 else blinds
IndexError: list index out of range
>>> blind = am43.search('02:EA:37:54:38:26')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/am43/search.py", line 6, in search
    return blinds[0] if len(addresses) == 1 else blinds
IndexError: list index out of range

Any hints?

Adam

**Comment by breitburg** [comment]
Hi. Are you sure that this is not a hardware problem? Have you tried connecting to your blinds by mobile app?

**Comment by DutchBear** [comment]
Hi Adam, I had the same issue. You need to use  lower case in the MAC address, now it works for me

**Comment by breitburg** [comment]
> Hi Adam, I had the same issue. You need to use lower case in the MAC address, now it works for me

Thank you for suggestion! I just released a [new version](https://github.com/breitburg/python-am43/releases/tag/v1.1.1) which contains a fix for this bug. 
Adam, hope this solves the problem 👌
